[project]
name = 'Stacks_010_imp'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.SIP_010]
path = 'contracts/SIP_010.clar'
clarity_version = 3
epoch = '3.2'

[contracts.ft-trait]
path = 'contracts/ft-trait.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
